Repository dinos-dev/dinos, pull requests merged in 2024-12, with the labels that each got.

#23 Feat: 애플 소셜로그인 연동 및 API 관련 모듈 추가
  ios/Podfile.lock
  ios/dinos.xcodeproj/project.pbxproj
  ios/dinos/Images.xcassets/AppIcon.appiconset/1024.png
  ios/dinos/Images.xcassets/AppIcon.appiconset/120 1.png
  ios/dinos/Images.xcassets/AppIcon.appiconset/120.png
  ios/dinos/Images.xcassets/AppIcon.appiconset/180.png
  ios/dinos/Images.xcassets/AppIcon.appiconset/40.png
  ios/dinos/Images.xcassets/AppIcon.appiconset/58.png
  ios/dinos/Images.xcassets/AppIcon.appiconset/60.png
  ios/dinos/Images.xcassets/AppIcon.appiconset/80.png
  ios/dinos/Images.xcassets/AppIcon.appiconset/87.png
  ios/dinos/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/dinos/Info.plist
  ios/dinos/dinos.entitlements
  package.json
  react-native-config.d.ts
  src/constants/ErrorCode.ts
  src/constants/ErrorMessages.ts
  src/hooks/socialLogin/index.ts
  src/hooks/socialLogin/useAppleAuth.ts
  src/hooks/socialLogin/useGoogleAuth.ts
  src/hooks/socialLogin/useNaverAuth.ts
  src/libs/apiErrorHandler.ts
  src/screens/common/LoginScreen.tsx
  src/screens/myPageScreens/MyPageScreen.tsx
  src/services/api.ts
  src/services/auth.ts
  src/services/interceptor.ts
  src/services/user.ts
  src/store/asynsStorage.ts
  src/store/authStore.ts
  src/types/auth.ts
  src/types/index.ts
  src/types/user.ts
  yarn.lock
Labels: feature

#24 Feat: 공통 UI 적용 #21
  .svgrrc
  android/app/src/main/assets/fonts/Pretendard-Bold.otf
  android/app/src/main/assets/fonts/Pretendard-ExtraBold.otf
  android/app/src/main/assets/fonts/Pretendard-Light.otf
  android/app/src/main/assets/fonts/Pretendard-Medium.otf
  android/app/src/main/assets/fonts/Pretendard-Regular.otf
  android/app/src/main/assets/fonts/Pretendard-SemiBold.otf
  android/link-assets-manifest.json
  declarations.d.ts
  ios/Podfile.lock
  ios/dinos.xcodeproj/project.pbxproj
  ios/dinos/Info.plist
  ios/link-assets-manifest.json
  metro.config.js
  package-lock.json
  package.json
  react-native.config.js
  src/App.tsx
  src/assets/fonts/Pretendard-Bold.otf
  src/assets/fonts/Pretendard-ExtraBold.otf
  src/assets/fonts/Pretendard-Light.otf
  src/assets/fonts/Pretendard-Medium.otf
  src/assets/fonts/Pretendard-Regular.otf
  src/assets/fonts/Pretendard-SemiBold.otf
  src/assets/icons/navBarIcon.tsx
  src/components/common/AppButton.tsx
  src/components/common/AppText.tsx
  src/constants/variables.ts
  src/navigators/members/MainTabNavigator.tsx
  src/screens/common/OnboardingScreen.tsx
  src/screens/mapScreens/MapScreen.tsx
  src/screens/matZipScreens/MatZipListScreen.tsx
  src/screens/myPageScreens/MyPageScreen.tsx
  src/screens/myPageScreens/ProfileScreen.tsx
  yarn.lock
Labels: feature, design

#20 Fix: 안드로이드 환경 네이버 로그인 버그 수정 #13
  package-lock.json
  package.json
  patches/@react-native-seoul+naver-login+4.0.4.patch
Labels: bug fix

#30 [Feature] 스플래시 스크린 및 아이콘 수정 #26
  android/app/src/main/res/drawable/splash.gif
  ios/dinos/Images.xcassets/Image.imageset/Contents.json
  ios/dinos/Images.xcassets/Image.imageset/splash100.png
  ios/dinos/Images.xcassets/Image.imageset/splash200.png
  ios/dinos/Images.xcassets/Image.imageset/splash300.png
  ios/dinos/LaunchScreen.storyboard
  src/assets/icons/mapStackIcon.tsx
  src/assets/icons/navBarIcon.tsx
  src/assets/image/splash.gif
  src/constants/NaviParams.ts
  src/constants/RoutePath.ts
  src/navigators/members/MainTabNavigator.tsx
  src/navigators/members/MembersNavigator.tsx
  src/navigators/members/sharedStack/HomeSharedStack.tsx
  src/screens/common/IosSplashScreen.tsx
  src/screens/homeScreen/HomeScreen.tsx
  src/screens/mapScreens/MapScreen.tsx
Labels: design

#35 Feat: 안드로이드 빌드 설정 및 마커 표시 오류 수정 #34
  .gitignore
  android/app/build.gradle
  android/app/src/main/java/com/dinos/MainActivity.kt
  android/gradle.properties
  ios/Podfile.lock
  package.json
  src/components/common/AppText.tsx
  src/navigators/root/RootNavigator.tsx
  src/screens/common/LoginScreen.tsx
  src/screens/mapScreens/MapScreen.tsx
  src/screens/myPageScreens/MyPageScreen.tsx
  src/screens/myPageScreens/ProfileScreen.tsx
  src/screens/myPageScreens/WithdrawalScreen.tsx
  yarn.lock
Labels: bug fix, feature, design

#37 Fix: asynsStorge, updateAccessToken 로직 수정 및 CheckBox 모듈 추가 #36
  src/constants/ErrorMessages.ts
  src/screens/myPageScreens/MyPageScreen.tsx
  src/screens/myPageScreens/WithdrawalScreen.tsx
  src/services/interceptor.ts
  src/store/asynsStorage.ts
  src/store/authStore.ts
Labels: bug fix, design
